# Generated by Django 2.1.2 on 2018-12-28 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 9, 6, 39, 368948, tzinfo=utc), verbose_name='date registered'),
            preserve_default=False,
        ),
    ]
